### PR TITLE
add haskell-language-server to shell.nix

### PR DESCRIPTION
**Pull request by kokobd**

### CODE REVIEW

**Comment by JackKelly-Bellroy** [comment]
Thanks for this. Should we update `compiler-nix-name ? "ghc922"` -> `compiler-nix-name ? "ghc924"` everywhere while we're looking at the nix files? It seems like the haskell.nix pin currently used wants to build GHC along the way.

If you get a better cache hit rate using `"ghc924"`, can you please add that change to this PR?

**Comment by kokobd** [comment]
> `"ghc924"`, can you please add that change to this PR?

Ah, yeah, of course.

**Comment by JackKelly-Bellroy** [comment]
I haven't got HIE set up on my machine, so I'll take your word for it that it's good. Thanks for the PR.

**Comment by kokobd** [comment]
Note that CI is not updated in this PR.
The latest `haskell-ci` from Hackage doesn't work for ghc-9.2.4. So we need to use the master version of `haskell-ci` to regenerate `haskell-ci.yml`. I have some problems specifying a master `haskell-ci`:

Add this to `buildInputs` in `shell.nix`
```nix
(haskell.lib.overrideSrc pkgs.haskellPackages.haskell-ci {
      src = fetchFromGitHub {
        owner = "haskell-CI";
        repo = "haskell-ci";
        rev = "c53a7f8fe06d0ea392fe35bafe217e24ed004286";
        sha256 = "sha256-WZKJAieuzrl8m39krWj+HLTu8PLGVjVBaKIXfSYw0DI=";
      };
    })
```
will result in
```
> Setup: Encountered missing or private dependencies:
       > Cabal-syntax >=3.8.1.0 && <3.9,
       > base-compat >=0.12 && <0.13,
       > cabal-install-parsers >=0.5 && <0.6,
       > optparse-applicative >=0.17.0.0 && <0.18
```

**Comment by JackKelly-Bellroy** [comment]
I suspected that might happen, so I merged as-is. For these open-source packages, I generally set `tested-with: ` to the latest minor versions that `haskell-ci` supports and ignore Nix. That way CI ensures that the package is usable by non-nix users.

**Pull request merged**
